server:
  port: 8080

services:
  auth: ${AUTH_SERVICE_URL:http://localhost:8082}
  aud: ${AUDITORIUM_SERVICE_URL:http://localhost:8081}
  notifier: ${NOTIFICATION_SERVICE_URL:http://localhost:8083}
  user: ${USER_SERVICE_URL:http://localhost:8084}
  certs-endpoint: ${services.auth}/certs

logging:
  level:
    root: info
